# Generated by Django 5.1.4 on 2025-01-29 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='teacher',
        ),
        migrations.AddField(
            model_name='timetable',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherclassassignment'),
            preserve_default=False,
        ),
    ]
