
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_conn
    networks:
      - mynet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: school_django_app
    command: 
        python manage.py runserver 0.0.0.0:8000 &&
        python manage.py migrate
    networks:
      - mynet
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  mynet:
    driver: bridge

