# Generated by Django 5.1.4 on 2025-01-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField()),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherclassassignment')),
            ],
        ),
    ]
