# Generated by Django 5.1.4 on 2025-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
