# Generated by Django 5.1.4 on 2025-01-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
