# Generated by Django 5.1.4 on 2025-01-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='test_paper',
            field=models.FileField(blank=True, null=True, upload_to='test_papers/'),
        ),
    ]
