# Generated by Django 5.1.4 on 2025-01-28 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_exam_marks'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentclassassignment')),
            ],
        ),
    ]
